// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDREvogWiG5SrWkfVYCD1Zk1_5ZN6YsN2k',
    appId: '1:892532734301:android:7475e67c85c1e0e99690b4',
    messagingSenderId: '892532734301',
    projectId: 'clinic-app-37727',
    storageBucket: 'clinic-app-37727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIR93M3b_nJTnm5iQws8vnfmzI2WHct54',
    appId: '1:892532734301:ios:5eff996a96579be99690b4',
    messagingSenderId: '892532734301',
    projectId: 'clinic-app-37727',
    storageBucket: 'clinic-app-37727.appspot.com',
    iosClientId: '892532734301-cqrbgf9rntfc9tsl8ie83if08kv56cqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinicReservationApp',
  );
}
